# Generated by Django 4.1.5 on 2023-01-08 08:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='aritcle',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
